### PR TITLE
Merge port of yew-autoprops in Yew to yew-autoprops

### LINKED ISSUE #3: #[autoprops_component] panics instead of making a proper error
As of writing, `yew-autoprops` uses `panic!()` macro to display errors to the user. This, however, is not intended and causes jarring error:
```rust
#[autoprops_component]
pub fn Example(i: u32) -> Html {
    html! {}
}

#[function_component]
pub fn App() -> Html {
    html! {
        <Example i={ 0 } />
    }
}
```

Error:
```
custom attribute panicked
message: Invalid argument: i : u32 (must be a reference)
```

# Possible Solutions
- Generate [`compile_error!()`](https://doc.rust-lang.org/std/macro.compile_error.html) instead of `panic!()`ing, this should cause a proper simple error to be displayed to the user of the library.
- In future, as Rust features stabilize, consider using [Diagnostic API](https://doc.rust-lang.org/proc_macro/struct.Diagnostic.html).

### LINKED ISSUE #7: Propless generic components require generic types to be used
Imagine a component like so:

```rust
#[autoprops_component]
pub fn Example<T: 'static>() -> Html {
    html! {}
}
```

As `T` is not used, Rust complains:

```md
parameter `T` is never used
consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`
```

- Is `Properties` (generic) struct still generated despite having no props?

At least, currently solvable with following code:

```rust
#[autoprops_component]
pub fn Example<T: 'static>(#[prop_or_default] _never: &PhantomData<T>) -> Html {
    html! {}
}
```

### LINKED ISSUE #8: Generic components require generic types to be PartialEq
[`#[derive]` is not perfect](https://blog.rust-lang.org/inside-rust/2022/04/04/lang-roadmap-2024.html#looking-forward) (funnily enough, I wrote this before I found the Rust blog quotation, where they mention it being "Perfect derive"), and Rust generates `impl`s with that derived trait also present for generic parameters (e.g. `derive(Clone)` does `impl<T: Clone> Clone for ...`). This would happen even for instances when the requirement for the generic parameter is not required (e.g. an `Rc<T>` field means the struct does not actually require `Clone` on `T`).

yew-autoprops does `#[derive(PartialEq)]`, which means when generating `impl`s Rust will place such a requirement on the generic parameters as well. This means following example will not be valid:

```rust
#[autoprops_component]
pub fn Example<T>(something: Rc<T>) {
    html! {}
}
```

As it comes up with the following error:

```md
can't compare `T` with `T`
no implementation for `T == T`
- required for `ExampleProps<T>` to implement `PartialEq`
- required by a bound in `Properties`
- consider further restricting type parameter `T`: `, T: std::cmp::PartialEq`
```

As all props fields are probably expected to be `PartialEq` (which isn't always the case with `derive`), I suggest manually implementing `PartialEq` for the props struct, containing comparisons for all the fields:

```rust
impl<T> PartialEq for ExampleProps<T> {
    fn eq(&self, other: &Self) -> bool {
        #pats_modified_1 = self; // adds _1 to each field, you also have to check that no name ends with _1/_2, otherwise add more underscores i guess
        #pats_modified_2 = other; // adds _2 to each field
        #comparisons // prop_1 == prop_2 && another_prop_1 == another_prop_2 && ...
    }
}
```

For generic parameters that are to be used directly as a type of a prop field, the user will have to declare them as `PartialEq`, which is the case for both `derive` and manual `impl` solutions.

This is a breaking problem (you cannot implement a custom `PartialEq`, unlike with non-autoprops props), and fixing it would improve experience of using generics by a lot compared to non-autoprops components.

### LINKED ISSUE #9: Main App cannot be autoprops
For consistency reasons, I tried to write following:

```rust
#[autoprops_component]
fn App() -> Html {
    html! {}
}
```

This comes up with following error on a CSR render:

```md
the function or associated item `new` exists for struct `Renderer<App>`, but its trait bounds were not satisfied
the following trait bounds were not satisfied:
`AppProps: std::default::Default`
- doesn't satisfy `AppProps: std::default::Default`
- consider annotating `AppProps` with `#[derive(Default)]`: `#[derive(Default)]`
```

This is probably due to fact that props struct generates for `App` even if there are no props (as mentioned in #7).
- Get rid of generating a props struct for propless autoprops components
- Otherwise possibly make empty struct a `Default`? (Also, consider manual `impl Default` where all types are `Default` - this is possible by listing `where type1: Default, type2: Default`, no matter how simple or complex the type is - you can even type out `where i32: Default` and it will still work)

### PR DESCRIPTION
**Pull request by cecton**
Fixes #8
Fixes #7
Fixes #9
Fixes #3
Related to https://github.com/yewstack/yew/pull/3505

### CODE REVIEW

**Comment by cecton** [comment]
cc @kirillsemyonkin

**Comment by kirillsemyonkin** [comment]
image

Seems like its generating an unexpected comma somewhere (be it struct or fn) when there are no props but there are generic types

**Comment by kirillsemyonkin** [comment]
Repro:
```rust
#[autoprops]
#[function_component]
pub fn Test<T>() -> Html {
    html! {}
}
```

**Comment by cecton** [comment]
@kirillsemyonkin fixed

**Comment by kirillsemyonkin** [comment]
I think to trigger CI you may wanted to rerun all jobs, sometimes I see that button in the actions section
image

**Comment by cecton** [comment]
No I really wanted to trigger the CI with a different commit hash ^_^

**Comment by cecton** [comment]
TIL that you need to add the rust version in swatinem/cache key for it to work properly :woman_facepalming: I have like 10 repos that are not doing that huh

**Comment by kirillsemyonkin** [comment]
image

Here is another one

**Comment by cecton** [comment]
Fixed

**Comment by kirillsemyonkin** [comment]
1. Autoprops does not require `-> Html` on the fn, nor `HtmlResult` works (seems like that is replaced by `Html`) - following does not work:

```
#[autoprops]
#[function_component]
pub fn Test() -> HtmlResult {
    Ok(html! {})
}
```

2. Defaults for fn generic type params are ignored by Rust, here are three cases (doesnt work, good; works, good; doesnt work, oops):

image
image
image

**Comment by cecton** [comment]
@kirillsemyonkin fixed

**Review by kirillsemyonkin — APPROVED** [review]
Works now for my entire project on every single component (10,280 lines of Yew code) - empty props, generics, non-cloning, auto cloning, public, private, etc etc

File: src/autoprops.rs [hunk 1]
```diff
@@ -0,0 +1,261 @@
...
+                        "cannot use `_` as field name",
+                    ));
+                }
+            }
+        }
+
+        let properties_name = syn::Ident::new(
+            &format!("{}Props", component_name),
+            proc_macro2::Span::call_site(),
+        );
```
Comment (hamza1311) [inline src/autoprops.rs:80]: The span should be `component_name.span()`, not `call_site`. Also consider using [`format_ident`](https://docs.rs/quote/latest/quote/macro.format_ident.html)

File: src/autoprops.rs [hunk 2]
```diff
@@ -0,0 +1,261 @@
...
+                    _ => None,
+                })
+                .collect::<Vec<_>>();
+            let phantom = sig.generics.type_params().next().is_some().then(|| {
+                quote! {
+                    phantom: _,
+                }
+            });
+            quote! {
+                #(#receivers,)* #properties_name {
```
Comment (hamza1311) [inline src/autoprops.rs:132]: What would the generated code be here? I'm not sure if the generated code is correct. To me, it seems that the following code generated:
```rust
self Props { ... }
```

File: src/autoprops.rs [hunk 3]
```diff
@@ -0,0 +1,261 @@
...
+            quote! {}
+        };
+        let clones = sig
+            .inputs
+            .iter()
+            .filter_map(|arg| match arg {
+                syn::FnArg::Typed(syn::PatType { pat, ty, .. })
+                    if !matches!(**ty, syn::Type::Reference(_)) =>
+                {
+                    Some(quote! { let #pat = ::std::clone::Clone::clone(#pat); })
```
Comment (hamza1311) [inline src/autoprops.rs:147]: I don't think the clone should be implicit here. If the clone is to be implicit, it should call `ImpicitClone` so when anything that doesn't implement `ImpicitClone` is attempted to be implicitly cloned, there is a compiler error

File: src/autoprops.rs [hunk 4]
```diff
@@ -0,0 +1,261 @@
...
+                fn eq(&self, rhs: &Self) -> ::std::primitive::bool {
+                    #(#fields_eq)* true
+                }
+            }
+        }
+    }
+
+    fn needs_a_properties_struct(&self) -> bool {
+        let syn::ItemFn { sig, .. } = &self.item_fn;
+        !sig.inputs.is_empty() || sig.generics.type_params().next().is_some()
```
Comment (hamza1311) [inline src/autoprops.rs:227]:
```rust
fn KnownValueWrapper<T>() -> Html
where 
    T: Component,
{
    let props = props!(<T as Component>::Properties, {
        some_known_value: todo!(),
       default_config: todo!(),
      // ...
    })
    html! { <T ..props /> }
}
```
This code is valid but would be unnecessarily end up creating a properties struct

**Review by hamza1311 — CHANGES_REQUESTED** [review]
Looks mostly good, just a couple of things that need addressing

File: src/autoprops.rs (hunk 2 above)
Comment (kirillsemyonkin) [reply src/autoprops.rs:132]: the whole branch is working on my big project, so i assume its correct unless i somehow dont hit this line

there is a comma not before * but inside group so id assume that if you are right it would at least be `self, Props { ... }`

File: src/autoprops.rs (hunk 3 above)
Comment (cecton) [reply src/autoprops.rs:147]: I can't figure out how to call it :persevere: halp please

```
fn main() {
    let x = 42_u32;
    <::implicit_clone::ImplicitClone as Clone>::clone(&x);
}
```

```
error[E0038]: the trait `ImplicitClone` cannot be made into an object
 --> src/main.rs:3:55
  |
3 |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
  |                                                       ^^ `ImplicitClone` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
  = note: required for the cast from `&u32` to `&dyn ImplicitClone`

error[E0277]: the size for values of type `dyn ImplicitClone` cannot be known at compilation time
   --> src/main.rs:3:55
    |
3   |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
    |     ------------------------------------------------- ^^ doesn't have a size known at compile-time
    |     |
    |     required by a bound introduced by this call
    |
    = help: the trait `Sized` is not implemented for `dyn ImplicitClone`
note: required by a bound in `clone`
   --> /home/cecile/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/clone.rs:147:18
    |
147 | pub trait Clone: Sized {
    |                  ^^^^^ required by this bound in `Clone::clone`
...
160 |     fn clone(&self) -> Self;
    |        ----- required by a bound in this associated function

error[E0038]: the trait `ImplicitClone` cannot be made into an object
 --> src/main.rs:3:6
  |
3 |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `ImplicitClone` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>

error[E0038]: the trait `ImplicitClone` cannot be made into an object
 --> src/main.rs:3:5
  |
3 |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `ImplicitClone` cannot be made into an object
  |
  = note: the trait cannot be made into an object because it requires `Self: Sized`
  = note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>

error[E0746]: return type cannot have an unboxed trait object
 --> src/main.rs:3:5
  |
3 |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
help: box the return type, and wrap all of the returned values in `Box::new`
  |
3 |     Box<<::implicit_clone::ImplicitClone as Clone>::clone>(&x);
  |     ++++                                                 +

error[E0782]: trait objects must include the `dyn` keyword
 --> src/main.rs:3:6
  |
3 |     <::implicit_clone::ImplicitClone as Clone>::clone(&x);
  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
help: add `dyn` keyword before this trait
  |
3 |     <dyn (::implicit_clone::ImplicitClone) as Clone>::clone(&x);
  |      +++++                               +

```

File: src/autoprops.rs (hunk 2 above)
Comment (cecton) [reply src/autoprops.rs:132]: yes the `,` is inside the parenthesis expressly for that reason, there is a test that validates that &self is actually passed to function_component properly and that I get the right error message. you can see it in the stderr file:

```
error: function components can't accept a receiver
 --> tests/function_component_attr/autoprops-fail.rs:6:23
  |
6 | fn CantAcceptReceiver(&self, b: bool) -> Html {
  |                       ^^^^^
```

File: src/autoprops.rs (hunk 4 above)
Comment (cecton) [reply src/autoprops.rs]: Ah I thought it was necessary for some reason. Ok I simply removed the condition and the tests passed ff74446ed11f21efde3387e7a1d3d07eda26a33f

File: src/autoprops.rs (hunk 1 above)
Comment (cecton) [reply src/autoprops.rs]: ah cool I didn't know. Done in 248b0c2c3c54889a690688c7cbb1a48ebf21f5d4

File: src/autoprops.rs (hunk 3 above)
Comment (kirillsemyonkin) [reply src/autoprops.rs:144]: `::implicit_clone::ImplicitClone::clone(&x)` doesn't work?
something like `Clone::clone(&x as &dyn ::implicit_clone::ImplicitClone)`?
`{ let _ = &x as &dyn ::implicit_clone::ImplicitClone; Clone::clone(&x) }`?
`{ fn implicit_clone<T: ImplicitClone>(value: &T) { value.clone() }; implicit_clone(&x) }` if nothing works? lol

Comment (cecton) [reply src/autoprops.rs:144]: - `::implicit_clone::ImplicitClone::clone(&x)` no
- `Clone::clone(&x as &dyn ::implicit_clone::ImplicitClone)` no
- `{ let _: &dyn ::implicit_clone::ImplicitClone = &x; Clone::clone(&x) }` no
- `{ let _ = &x as &dyn ::implicit_clone::ImplicitClone; Clone::clone(&x) }` no
- `{ fn implicit_clone<T: ::implicit_clone::ImplicitClone>(value: &T) -> T { value.clone() } implicit_clone(&x) }` that worked!

Comment (cecton) [reply src/autoprops.rs:144]: I feel it's not a very elegant solution :(

Comment (cecton) [reply src/autoprops.rs:144]: Conceptually I'm not sure if this change is good actually. ImplicitClone is used by Yew to allow the type to be implicitly cloned when it's passed by reference in the `html!` macro. It's not used for "restricting" the input of the user. If I could have avoided introducing a new trait, I would have so I'm not sure that we actually *want* to restrict things here

Also the "help" message is replaced by an obscure "note":

```patch
diff --git a/tests/function_component_attr/autoprops-fail.stderr b/tests/function_component_attr/autoprops-fail.stderr
index d87685c..1aa9c95 100644
--- a/tests/function_component_attr/autoprops-fail.stderr
+++ b/tests/function_component_attr/autoprops-fail.stderr
@@ -41,19 +41,45 @@ note: struct `crate::private_module::CompPrivateTest` exists but is inaccessible
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not accessible
    = note: this error originates in the attribute macro `::yew::function_component` (in Nightly builds, run with -Z macro-backtrace for more info)
 
-error[E0277]: the trait bound `NotClonable: Clone` is not satisfied
+error[E0277]: the trait bound `NotClonable: ImplicitClone` is not satisfied
   --> tests/function_component_attr/autoprops-fail.rs:40:19
    |
 38 | #[autoprops]
    | ------------ required by a bound introduced by this call
 39 | #[function_component]
 40 | fn TypeIsNotClone(stuff: NotClonable) -> Html {
-   |                   ^^^^^ the trait `Clone` is not implemented for `NotClonable`
+   |                   ^^^^^ expected an implementor of trait `ImplicitClone`
    |
-help: consider annotating `NotClonable` with `#[derive(Clone)]`
+note: required by a bound in `<TypeIsNotClone as FunctionProvider>::run::inner::implicit_clone`
+  --> tests/function_component_attr/autoprops-fail.rs:38:1
    |
-36 | #[derive(Clone)]
+38 | #[autoprops]
+   | ^^^^^^^^^^^^ required by this bound in `<TypeIsNotClone as FunctionProvider>::run::inner::implicit_clone`
+   = note: this error originates in the attribute macro `autoprops` (in Nightly builds, run with -Z macro-backtrace for more info)
+help: consider borrowing here
+   |
+40 | fn TypeIsNotClone(&stuff: NotClonable) -> Html {
+   |                   +
+
+error[E0277]: the trait bound `NotPartialEq: ImplicitClone` is not satisfied
+  --> tests/function_component_attr/autoprops-fail.rs:52:23
+   |
+50 | #[autoprops]
+   | ------------ required by a bound introduced by this call
+51 | #[function_component]
+52 | fn TypeIsNotPartialEq(stuff: NotPartialEq) -> Html {
+   |                       ^^^^^ expected an implementor of trait `ImplicitClone`
+   |
+note: required by a bound in `<TypeIsNotPartialEq as FunctionProvider>::run::inner::implicit_clone`
+  --> tests/function_component_attr/autoprops-fail.rs:50:1
+   |
+50 | #[autoprops]
+   | ^^^^^^^^^^^^ required by this bound in `<TypeIsNotPartialEq as FunctionProvider>::run::inner::implicit_clone`
+   = note: this error originates in the attribute macro `autoprops` (in Nightly builds, run with -Z macro-backtrace for more info)
+help: consider borrowing here
    |
+52 | fn TypeIsNotPartialEq(&stuff: NotPartialEq) -> Html {
+   |                       +
 
 error[E0369]: binary operation `==` cannot be applied to type `NotPartialEq`
   --> tests/function_component_attr/autoprops-fail.rs:52:30
```

Comment (cecton) [reply src/autoprops.rs:144]: The time was not wasted though because it did reveal another missing impl on primitive types: https://github.com/yewstack/implicit-clone/pull/42

Comment (kirillsemyonkin) [reply src/autoprops.rs:144]: > I feel it's not a very elegant solution :(

That fn could be moved to ImplicitClone, like `std::mem::copy` and `std::mem::drop` (I thought `std::mem::move` also exists), all of which have a doc that says "This function is not magic; it is literally defined as..."

Comment (cecton) [reply src/autoprops.rs:144]: Created https://github.com/yewstack/implicit-clone/pull/44

Comment (cecton) [reply src/autoprops.rs]: Fixed in 45682cc

**Comment by cecton** [comment]
@hamza1311 @kirillsemyonkin ok I think this is ready now

File: src/autoprops.rs [hunk 5]
```diff
@@ -0,0 +1,260 @@
...
+        };
+        let clones = sig
+            .inputs
+            .iter()
+            .filter_map(|arg| match arg {
+                syn::FnArg::Typed(syn::PatType { pat, ty, .. })
+                    if !matches!(**ty, syn::Type::Reference(_)) =>
+                {
+                    Some(quote! {
+                        let #pat = ::implicit_clone::ImplicitClone::implicit_clone(#pat);
```
Comment (futursolo) [inline src/autoprops.rs:145]: `implicit_clone` needs to be re-exported from `yew_autoprops`. This ensures `implicit_clone` here is referring to a version compatible with the generated code.

Comment (cecton) [reply src/autoprops.rs:145]: I can't. yew-autoprops is purely a proc_macro crate so I cannot export it.

But what I can do is to use the re-export from yew. I don't know if that's any better?

Comment (cecton) [reply src/autoprops.rs:145]: Yes I think that's better because it's using the same version than Yew from which we do a proc macro... makes sense

**Comment by kirillsemyonkin** [comment]
What is the current status of this?

File: tests/function_component_attr/autoprops-fail.stderr [hunk 6]
```diff
@@ -0,0 +1,72 @@
+error: function components can't accept a receiver
+ --> tests/function_component_attr/autoprops-fail.rs:7:23
+  |
+7 | fn CantAcceptReceiver(&self, b: bool) -> Html {
+  |                       ^^^^^
+
+error: could not find #[function_component] attribute in function declaration (#[autoprops] must be placed *before* #[function_component])
```
Comment (futursolo) [inline tests/function_component_attr/autoprops-fail.stderr:7]: I think we cannot enforce a function_component macro by reading the macro name as `function_component` can be renamed with `as` and can be implemented via other macros like `stylist::yew::styled_component`.

File: src/autoprops.rs [hunk 7]
```diff
@@ -0,0 +1,260 @@
...
+            .collect::<Vec<_>>();
+        let type_params = sig
+            .generics
+            .type_params()
+            .map(|param| &param.ident)
+            .collect::<Vec<_>>();
+        let phantom = (!type_params.is_empty()).then(|| {
+            quote! {
+                #[prop_or_default]
+                #vis phantom: ::std::marker::PhantomData <( #(#type_params),* )>,
```
Comment (futursolo) [inline src/autoprops.rs:193]:
```suggestion
                #vis __yew_auto_phantom: ::std::marker::PhantomData <( #(#type_params),* )>,
```

This type should be prefixed to minimise chance of collision.

File: src/autoprops.rs [hunk 8]
```diff
@@ -0,0 +1,260 @@
...
+        }
+
+        let (impl_generics, type_generics, where_clause) = sig.generics.split_for_impl();
+        let fields = sig
+            .inputs
+            .iter()
+            .filter_map(|arg| match arg {
+                syn::FnArg::Typed(syn::PatType { attrs, pat, ty, .. }) => match ty.as_ref() {
+                    syn::Type::Reference(syn::TypeReference { elem, .. }) => {
+                        Some(quote! { #(#attrs)* #vis #pat: #elem, })
```
Comment (futursolo) [inline src/autoprops.rs:178]: It is debatable of whether attributes of function arguments should be applied to the function itself or to properties struct definition. `#[props_...]` should be transferred to struct definition, however, I am not sure about other attributes.

All of the following order of attribute macros would result in different code generation behaviour to `#[foreign_trait]` if `#[foreign_trait]` will process attributes based on `#[foreign_trait_attr]`.

```rust
#[foreign_trait]
#[autoprops]
#[function_component]
fn Comp(#[foreign_trait_attr] arg: Arg) -> Html {}
```

```rust
#[autoprops]
#[foreign_trait]
#[function_component]
fn Comp(#[foreign_trait_attr] arg: Arg) -> Html {}
```

```rust
#[autoprops]
#[function_component]
#[foreign_trait]
fn Comp(#[foreign_trait_attr] arg: Arg) -> Html {}
```

File: tests/function_attr_test.rs [hunk 9]
```diff
@@ -0,0 +1,13 @@
+#[allow(dead_code)]
+#[test]
+fn tests_pass() {
+    let t = trybuild::TestCases::new();
+    t.pass("tests/function_component_attr/*-pass.rs");
```
Comment (futursolo) [inline tests/function_attr_test.rs:5]: Pass tests should also only be run with MSRV.
Rustc may introduce additional lints over the time to fail pass tests.

File: src/autoprops.rs (hunk 8 above)
Comment (kirillsemyonkin) [reply src/autoprops.rs:178]: Yes, `#[foreign_trait]` (should've been called `#[foreign_proc_macro]`?) will make it be handled differently in those 3 cases, and this is up to the user to remember. You would not swap lines of function's code without noticing that it may change its logic. As I was writing this comment, I came to a realisation that it does not really make sense to put anything other than `#[function_component]` inside `#[autoprops]`, and any other `#[foreign_trait]` should transform the fn before `#[autoprops]` kicks in, where `#[autoprops]` would not even realise that there is any work of the external proc macros.

File: tests/function_attr_test.rs (hunk 9 above)
Comment (kirillsemyonkin) [reply tests/function_attr_test.rs:5]: Tests breaking somehow to me sounds like a good idea, despite being slightly annoying upon trying to perform an unrelated PR ([already happened with clippy before](https://github.com/yewstack/implicit-clone/pull/35)). Maybe have them run under both MSRV and latest stable so we can see whether such a lint change occured?

File: src/autoprops.rs (hunk 8 above)
Comment (kirillsemyonkin) [reply src/autoprops.rs:178]: Maybe ban any `#[foreign_trait_attr]`s?

File: tests/function_attr_test.rs (hunk 9 above)
Comment (cecton) [reply tests/function_attr_test.rs:5]: @kirillsemyonkin it's already what I did here

But in Yew we only run them against MSRV.

imo it's best to run it on both because we need the thing to keep working on stable and to be alerted asap when it's not. 

I don't mind restricting this test to MSRV though.

File: src/autoprops.rs (hunk 8 above)
Comment (cecton) [reply src/autoprops.rs:178]: I think it's a bit too hypothetical. It might be best to wait that an actual come up?

File: src/autoprops.rs (hunk 7 above)
Comment (cecton) [reply src/autoprops.rs]: Done in e323bee

File: tests/function_component_attr/autoprops-fail.stderr (hunk 6 above)
Comment (cecton) [reply tests/function_component_attr/autoprops-fail.stderr]: Done in e8fe2f0

Comment (cecton) [reply tests/function_component_attr/autoprops-fail.stderr]: Though imo we should use a separate proc macro instead of outputting the function component from an extended macro. This allows better composition:

```
#[styled_component]
#[autoprops]
#[function_component]
fn MyStyledComponent() -> Html {
    html! {<div class={css!("color: red;")}>{"Hello World!"}</div>}
}
```

File: src/autoprops.rs (hunk 8 above)
Comment (kirillsemyonkin) [reply src/autoprops.rs:159]: @cecton
The
> I am OK with leaving the implementation as-is

probably means its ok with us i guess, and can be marked as resolved, but
> Maybe ban any `#[foreign_trait_attr]`s inside `#[autoprops]`?

kinda makes sense since the autoprops fn arguments dont behave like any other fn arguments (since they get transformed into struct, destructure, etc, anything but fn arguments as-is), if you are still not sure then we can leave it as it already is done

File: tests/function_component_attr/autoprops-fail.stderr (hunk 6 above)
Comment (kirillsemyonkin) [reply tests/function_component_attr/autoprops-fail.stderr]: yeah `#[styled] #[autoprops] #[component]` / `#[autoprops] #[styled] #[component]` ([yewstack/yew/#3447](https://github.com/yewstack/yew/pull/3447) would be a breaking change btw so stylist would need to be updated anyway) should compose well, but its up to @futursolo to make a breaking change just for that

File: src/autoprops.rs (hunk 8 above)
Comment (cecton) [reply src/autoprops.rs:159]: I'm not sure because if someone makes another proc macro that can be used in the composition here, like:

```
#[foreign_trait]
#[autoprops]
#[function_component]
fn Comp(#[foreign_trait_attr] arg: Arg) -> Html {}
```

It could be that the foreign trait attr will be properly located. I think it's best to revisit this in the future and avoid being too restrictive now. When you are too restrictive you block a path and changing path requires a breaking change. While if you don't commit yet, you can still leave this as "undefined" and pick a direction later on without making a breaking change

Comment (kirillsemyonkin) [reply src/autoprops.rs:159]: @cecton i already mentioned this for your example

> `#[foreign_trait]` should transform the fn before `#[autoprops]` kicks in, where `#[autoprops]` would not even realise that there is any work of the external proc macros

Comment (cecton) [reply src/autoprops.rs:159]: ok I think there is miscommunication here. What do I need to do exactly? ^_^

Comment (kirillsemyonkin) [reply src/autoprops.rs:159]: The idea is that foreign attrs (everything except `#[prop_or...]`, which are intentional - autoprops's fn arg attr `#[prop_or...]` turns into yew's struct field attr `#[prop_or...]`) that were applied to fn args now get applied to struct fields in your generated code, which sounds wrong. The idea is to ban anything but the `#[prop_or(...)]` because there arent any fn args like there were before autoprops transformation (e.g. before transformation `a: ..., b: ...`, after transformation `Props { pub a: ..., pub b: ... }`, fn args and struct fields are completely different things, so none fn arg attrs would work on struct field attrs, especially since we cannot know what should be a `#[derive(ForeignTrait)]`, but we know that `#[prop_or...]` works for `#[derive(Properties)]`).

Reason it works in your example is that if you put foreign attr before autoprops, it should strip those fn arg attrs out, so essentially autoprops only sees

```rust
#[autoprops]
#[function_component]
fn Comp(arg: Arg) -> Html {}
```

Comment (cecton) [reply src/autoprops.rs:159]: And leaving things as is for now and see how it goes is not acceptable? We have to commit into banning these other attrs **now**? We can't keep this as an open question for later?

And what should I do? Raise an error or strip them silently? What if the user use `#[cfg(...)]`, I assume I still need to keep those?

Comment (kirillsemyonkin) [reply src/autoprops.rs:159]: > What if the user use `#[cfg(...)]`

Should this be handled by autoprops too (copy to both destructure, struct definition, etc)? This asks for a separate PR/Issue open

> Raise an error or strip them silently?

Error, stripping them silently will be very unwanted

> And leaving things as is for now and see how it goes is not acceptable?

Arguable tbf, I do think it sounds wrong to put a fn arg attr to struct field without telling anything about it to the struct, I think it will error by itself because of this, so it might be fine, but the error would make not a lot of sense to the user, which is why I think its a good idea to fix it before making the change public, but if you are still not sure:

> We can't keep this as an open question for later?

As mentioned,

> I am OK with leaving the implementation as-is

> probably means its ok with us i guess, and can be marked as resolved

Comment (cecton) [reply src/autoprops.rs:159]: Ok I made an issue because clearly it's complicated https://github.com/yewstack/yew-autoprops/issues/11

File: tests/function_attr_test.rs (hunk 9 above)
Comment (cecton) [reply tests/function_attr_test.rs:5]: @futursolo do you agree with the argument or you still prefer the passing test to run only on MSRV?

**Comment by cecton** [comment]
@yewstack/yew can I have a final review on this?

**Comment by kirillsemyonkin** [comment]
> @yewstack/yew can I have a final review on this?

Can we skip such a review since it is more-or-less separate from Yew and proceed to merge? We can have extra merges later, independent of Yew's slow cycle
